# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aaron',
                'doc_host': 'https://aaronsgithub.github.io',
                'git_url': 'https://github.com/aaronsgithub/aaron',
                'lib_path': 'aaron'},
  'syms': {'aaron.core': {'aaron.core.foo': ('core.html#foo', 'aaron/core.py')}}}
